### ISSUE TITLE
Add linters

### ISSUE THREAD

**Issue by MarekBleschke** [MarekBleschke/pygame-demos#1]
Add black, mypy and flake8.

### Tasks
- [ ] add linters and make code compliant with them
- [ ] setup GitHub workflow with linters check
- [ ] set linters check in branch protection rules
