### ISSUE TITLE
Handle finishing the game

### ISSUE THREAD

**Issue by MarekBleschke** [MarekBleschke/pygame-demos#3]
### Tasks

- [ ] disable further marking the tiles after game ends
- [ ] add information about winner / draw
- [ ] provide actions after game ends: play again, exit
